apiVersion: v1
kind: Secret
metadata:
  name: openldap-secret
  namespace: {{ include "openldap.namespace" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: {{ .Values.global.ldap.adminPassword | quote }}
  LDAP_CONFIG_PASSWORD: {{ .Values.global.ldap.configPassword | quote }}
