apiVersion: v1
kind: Namespace
metadata:
  name: dev-platform
  labels:
    name: dev-platform
    {{- if .Values.global.istio.enabled }}
    istio-injection: enabled
    {{- end }}
    {{- include "devplatform.labels" . | nindent 4 }}
{{- if .Values.global.istio.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
    {{- include "devplatform.labels" . | nindent 4 }}
{{- end }}
