apiVersion: v1
kind: Secret
metadata:
  name: gitea-ldap-secret
  namespace: {{ include "gitea.namespace" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_BIND_PASSWORD: {{ .Values.global.ldap.adminPassword | quote }}
  GITEA_ADMIN_PASSWORD: {{ .Values.global.gitea.adminPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-keycloak-client-secret
  namespace: {{ include "gitea.namespace" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLIENT_SECRET: {{ .Values.global.keycloak.clientSecrets.giteaService | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: {{ include "gitea.namespace" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_TOKEN: "gitea_admin_token_change_me_after_first_login"
