apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-manager-config
  namespace: {{ include "ldap-manager.namespace" . }}
  labels:
    {{- include "ldap-manager.labels" . | nindent 4 }}
data:
  LDAP_URL: "ldap://openldap1.dev-platform.svc.cluster.local:389"
  LDAP_BASE_DN: {{ .Values.global.ldap.baseDN | quote }}
  LDAP_BIND_DN: {{ .Values.global.ldap.bindDN | quote }}
  PORT: "8080"
  METRICS_PORT: "9090"
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  LDAP_POOL_SIZE: {{ .Values.poolSize | quote }}
  STARTING_UID: {{ .Values.startingUID | quote }}
  STARTING_GID: {{ .Values.startingGID | quote }}
