apiVersion: v1
kind: Secret
metadata:
  name: ldap-manager-secret
  namespace: {{ include "ldap-manager.namespace" . }}
  labels:
    {{- include "ldap-manager.labels" . | nindent 4 }}
type: Opaque
data:
  LDAP_BIND_PASSWORD: {{ .Values.global.ldap.adminPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | b64enc | quote }}
