apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldap-manager.fullname" . }}
  namespace: {{ include "ldap-manager.namespace" . }}
  labels:
    {{- include "ldap-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ldap-manager.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: 9090
    protocol: TCP
