apiVersion: v1
kind: Secret
metadata:
  name: gitea-service-secret
  namespace: {{ include "gitea-service.namespace" . }}
  labels:
    {{- include "gitea-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITEA_ADMIN_PASSWORD: {{ .Values.global.gitea.adminPassword | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  GITEA_WEBHOOK_SECRET: "change-me-webhook-secret"
  KEYCLOAK_CLIENT_SECRET: {{ .Values.global.keycloak.clientSecrets.giteaService | quote }}
