apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: {{ include "gitea-service.namespace" . }}
  labels:
    {{- include "gitea-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gitea-service.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: 9091
    protocol: TCP
