apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-http
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`keycloak.localhost`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080
      middlewares:
        - name: keycloak-headers
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: keycloak-headers
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "http"
      X-Forwarded-Host: "keycloak.localhost"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-metrics
  namespace: {{ include "auth.namespace" . }}
  labels:
    app: keycloak
    monitoring: prometheus
    {{- include "auth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: keycloak
