apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.global.keycloak.adminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.global.keycloak.adminPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_DB_PASSWORD: {{ .Values.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  gitea-service-secret: {{ .Values.global.keycloak.clientSecrets.giteaService | quote }}
  ldap-manager-secret: {{ .Values.global.keycloak.clientSecrets.ldapManager | quote }}
  frontend-admin-secret: {{ .Values.global.keycloak.clientSecrets.frontendAdmin | quote }}
