apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-role
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-rolebinding
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-role
subjects:
  - kind: ServiceAccount
    name: keycloak
    namespace: {{ include "auth.namespace" . }}
