apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "auth.namespace" . }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
