apiVersion: v1
kind: Service
metadata:
  name: codeserver-service
  namespace: {{ include "codeserver.namespace" . }}
  labels:
    {{- include "codeserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "codeserver.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: 8082
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: 9092
    protocol: TCP
