apiVersion: v1
kind: Service
metadata:
  name: codeserver-service
  namespace: dev-platform
  labels:
    app: codeserver-service
spec:
  type: LoadBalancer
  selector:
    app: codeserver-service
  ports:
    - name: http
      port: 30012
      targetPort: 8082
      protocol: TCP
    - name: metrics
      port: 30014
      targetPort: 9092
      protocol: TCP
